TEXTS = {
    "en": {
        "welcome": "Welcome to ArchAgent\nSend a photo of your space or building to start.",
        "photo_received": "Photo received.\nAnalyzing the scene...",
        "scene_detected": "Detected scene type:",
        "choose_style": "Choose a style:",
        "ask_change": "Great.\nNow tell me what you want to change.\nYou can type or send a voice message.",
        "send_photo_first": "Please send a photo first.",
        "choose_style_first": "Please choose a style first.",
        "generating": "Generating design concept...",
        "result_caption": "Here is your AI-edited design concept.",
        "voice_processing": "Processing your voice message...",
        "voice_failed": "Voice transcription failed.",
        "ai_failed": "AI generation failed.",
        "materials_title": "Suggested materials:",
        "cost_title": "Estimated cost range:",
        "stores_title": "Suggested nearby supplier types:",
        "wallet_prompt": "Choose your next step:",
        "coming_pay": "TON payment panel is ready in the web app.",
        "coming_mint": "NFT minting panel is ready in the web app.",
        "open_panel": "Open TON Panel",
    },
    "fa": {
        "welcome": "به ArchAgent خوش آمدید\nبرای شروع یک عکس از فضا یا ساختمان خود ارسال کنید.",
        "photo_received": "عکس دریافت شد.\nدر حال تحلیل صحنه...",
        "scene_detected": "نوع فضا تشخیص داده شد:",
        "choose_style": "سبک را انتخاب کن:",
        "ask_change": "عالی.\nحالا بگو چه چیزی را می‌خواهی تغییر بدهی.\nمی‌توانی تایپ کنی یا ویس بفرستی.",
        "send_photo_first": "لطفاً اول یک عکس بفرست.",
        "choose_style_first": "لطفاً اول سبک را انتخاب کن.",
        "generating": "در حال تولید طرح...",
        "result_caption": "این هم طرح ویرایش‌شده با هوش مصنوعی.",
        "voice_processing": "در حال پردازش ویس...",
        "voice_failed": "تبدیل ویس به متن ناموفق بود.",
        "ai_failed": "تولید طرح با هوش مصنوعی ناموفق بود.",
        "materials_title": "متریال پیشنهادی:",
        "cost_title": "بازه تقریبی هزینه:",
        "stores_title": "نوع فروشگاه‌های پیشنهادی نزدیک:",
        "wallet_prompt": "مرحله بعدی را انتخاب کن:",
        "coming_pay": "پنل پرداخت TON داخل وب‌اپ آماده است.",
        "coming_mint": "پنل مینت NFT داخل وب‌اپ آماده است.",
        "open_panel": "باز کردن پنل TON",
    },
    "ar": {
        "welcome": "مرحبا بك في ArchAgent\nأرسل صورة للمكان أو المبنى للبدء.",
        "photo_received": "تم استلام الصورة.\nجارٍ تحليل المشهد...",
        "scene_detected": "تم اكتشاف نوع المشهد:",
        "choose_style": "اختر النمط:",
        "ask_change": "ممتاز.\nالآن أخبرني ماذا تريد أن تغيّر.\nيمكنك الكتابة أو إرسال رسالة صوتية.",
        "send_photo_first": "يرجى إرسال صورة أولاً.",
        "choose_style_first": "يرجى اختيار النمط أولاً.",
        "generating": "جارٍ إنشاء التصميم...",
        "result_caption": "هذا هو التصميم المعدل بالذكاء الاصطناعي.",
        "voice_processing": "جارٍ معالجة الرسالة الصوتية...",
        "voice_failed": "فشل تحويل الصوت إلى نص.",
        "ai_failed": "فشل إنشاء التصميم بالذكاء الاصطناعي.",
        "materials_title": "المواد المقترحة:",
        "cost_title": "النطاق التقريبي للتكلفة:",
        "stores_title": "أنواع الموردين القريبين المقترحين:",
        "wallet_prompt": "اختر الخطوة التالية:",
        "coming_pay": "لوحة دفع TON جاهزة داخل تطبيق الويب.",
        "coming_mint": "لوحة سك NFT جاهزة داخل تطبيق الويب.",
        "open_panel": "فتح لوحة TON",
    },
    "ru": {
        "welcome": "Добро пожаловать в ArchAgent\nОтправьте фото пространства или здания.",
        "photo_received": "Фото получено.\nАнализ сцены...",
        "scene_detected": "Тип сцены:",
        "choose_style": "Выберите стиль:",
        "ask_change": "Отлично.\nТеперь скажите, что хотите изменить.\nМожно написать или отправить голос.",
        "send_photo_first": "Сначала отправьте фото.",
        "choose_style_first": "Сначала выберите стиль.",
        "generating": "Создание дизайна...",
        "result_caption": "Вот ваш AI-дизайн.",
        "voice_processing": "Обработка голосового сообщения...",
        "voice_failed": "Не удалось распознать голос.",
        "ai_failed": "Ошибка генерации AI.",
        "materials_title": "Рекомендуемые материалы:",
        "cost_title": "Примерная стоимость:",
        "stores_title": "Рекомендуемые поставщики:",
        "wallet_prompt": "Выберите следующий шаг:",
        "coming_pay": "Панель оплаты TON готова в web app.",
        "coming_mint": "Панель минта NFT готова в web app.",
        "open_panel": "Открыть TON панель",
    },
}