const qs = new URLSearchParams(window.location.search);
const projectId = qs.get("project_id");
const userId = qs.get("user_id");

document.getElementById("projectId").textContent = projectId || "-";
document.getElementById("userId").textContent = userId || "-";

const statusEl = document.getElementById("status");
const walletEl = document.getElementById("walletAddress");

const tonConnectUI = new TON_CONNECT_UI.TonConnectUI({
  manifestUrl: `${window.location.origin}/webapp/tonconnect-manifest.json`,
  buttonRootId: "ton-connect"
});

let walletAddress = null;

tonConnectUI.onStatusChange(wallet => {
  if (wallet?.account?.address) {
    walletAddress = wallet.account.address;
    walletEl.textContent = walletAddress;
    statusEl.textContent = "Wallet connected.";
  } else {
    walletAddress = null;
    walletEl.textContent = "Not connected";
    statusEl.textContent = "Wallet disconnected.";
  }
});

document.getElementById("payBtn").addEventListener("click", async () => {
  try {
    if (!walletAddress) {
      statusEl.textContent = "Please connect wallet first.";
      return;
    }

    const res = await fetch("/api/payment/create", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        user_id: userId,
        project_id: projectId,
        amount_ton: "0.2",
        purpose: "pro_unlock"
      })
    });

    const payment = await res.json();
    const amountNano = (0.2 * 1e9).toString();

    const tx = await tonConnectUI.sendTransaction({
      validUntil: Math.floor(Date.now() / 1000) + 300,
      messages: [
        {
          address: payment.merchant_address,
          amount: amountNano
        }
      ]
    });

    await fetch("/api/payment/verify", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        payment_id: payment.payment_id,
        tx_hash: tx?.boc || "demo_tx_hash"
      })
    });

    statusEl.textContent = "Payment sent successfully.";
  } catch (err) {
    statusEl.textContent = "Payment failed:\n" + String(err);
  }
});

document.getElementById("mintBtn").addEventListener("click", async () => {
  try {
    if (!walletAddress) {
      statusEl.textContent = "Please connect wallet first.";
      return;
    }

    const title = prompt("NFT title", "ArchAgent Design");
    const description = prompt("NFT description", "Generated by ArchAgent");

    const res = await fetch("/api/nft/mint", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        project_id: projectId,
        owner_wallet: walletAddress,
        title,
        description,
        image_url: "https://placehold.co/1024x1024/png"
      })
    });

    const data = await res.json();
    statusEl.textContent = "NFT mint request created.\nNFT ID: " + data.nft_id;
  } catch (err) {
    statusEl.textContent = "NFT request failed:\n" + String(err);
  }
});